### PR TITLE
WIP: allow checking po files

### PR DESCRIPTION
**Pull request by Jean-Abou-Samra**
TODO: tests

This finds almost 100 issues in python-docs-fr, mostly about usage of the default role.

Open question is whether polib should be an optional dependency.

### CODE REVIEW

**Comment by Jean-Abou-Samra** [comment]
https://github.com/python/python-docs-fr/pull/1824 fixes most of these issues in `python-docs-fr`.

**Comment by JulienPalard** [comment]
> Open question is whether polib should be an optional dependency.

I think so, as it's clearly not the main use of sphinx-lint.

We'll just have to write a nice warning message like "Skipping po file: please install sphinx-lint[po] if you want for sphinx-lint to check them too", because it could happen that a po file is in the checked tree, I don't want sphinx-lint to `exit(1)` in this case. I think I would enjoy having the error being printed like any other errors, "on line 1", so it can even be read from the IDE if someone uses sphinx-lint from an IDE.

**Review by ezio-melotti — COMMENTED** [review]
This seems a useful feature -- I was just looking into linting some of the CPython translations --, however I think it would be better to make it optional and hide it behind an explicit flag, e.g. `--check-po-files`.

If the flag is specified it could check if `polib` is installed and give an error if it isn't.  If it's installed it can include `.po` files in the check.

Regarding the implementation I think it would be better if there was a bit less coupling, but that will likely make the PR more complex.  Since there probably aren't many other file types we want to check, then I'd say the current implementation is ok -- we can always refactor later if we add more file types.

**Comment by Jean-Abou-Samra** [comment]
I'm a bit short on time right now. I hope to pick this up, but it might not be very soon. (But feel free to beat me to it.)

**Comment by JulienPalard** [comment]
I've "merged" your PR, with a slightly different approch as the code has evolved a lot since then.

Thanks for the PR, the idea, and the initial implementation!!

**Comment by JulienPalard** [comment]
@Jean-Abou-Samra I'm fixing those found in python-docs-fr and will open a PR to add sphinx-lint to the CI of python-docs-fr (and propose it to other translations).

**Pull request closed without merging**
