### PR TITLE
Add tox for easy testing of multiple Python versions

### PR DESCRIPTION
**Pull request by hugovk**
For example:

```sh
# Test with one Python version (e=environment)
tox -e py312

# Test with all installed versions
tox

# Test with all installed versions, in parallel
tox -p auto
```

Also use tox on the CI, test with coverage, and upload coverage to Codecov.

Coverage is an impressive 91.29%!

Also adds PyPy3.10 to the test matrix.

### CODE REVIEW

**Comment by ezio-melotti** [comment]
Does this PR replace #68?

**Comment by hugovk** [comment]
It replaces some of it, but that also includes some linting stuff. I was also planning on adding some pre-commit based linting after this is merged.

**Comment by JulienPalard** [comment]
I have a very bad experience with pytest-cov running in parallel (inside `tox -p all`), to the point I took the habit to just use `coverage run -m pytest` (which is not much more to type).

See: https://github.com/pytest-dev/pytest-cov/issues/416

Is your experience different? Maybe it has been somehow fixed by now?

**Comment by hugovk** [comment]
Hmm, I often use `tox -p auto` and haven't noticed that.

I added this to the top of `sphinxlint.py`:

```python
import sys

if sys.version_info >= (3, 10):
    a = 1
else:
    a = 2
```

Ran `tox -p all` and it showed as covered:

image

Maybe it's fixed? Or I'm not running into it for some reason?

**Comment by JulienPalard** [comment]
> Maybe it's fixed? Or I'm not running into it for some reason?

Maybe.

If we spot sqlite/coverage related errors, we know how to fix it (but just not using pytest-cov).

Let's try your way.

**Comment by hugovk** [comment]
Sounds good.

**Pull request merged**
